os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
addons:
  services:
    - mongod

script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
