os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
addons:
  services:
    - mongod
before_script:
  - sleep 15
  - mongo test --eval 'db.createUser( { user: "test", pwd: "test", roles: [ ] })'
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
